---
title: "Movie Recommendation using Recommendation systems"
author: "Batch 47 - INSOFE Lab"
date: "28th October 2018"
output:
  html_document:
    toc: yes
    toc_depth: '3'
    toc_float: yes
---

# Clear Environment

```{r}
rm(list=ls(all=T))
```

# Loading Libraries

```{r}
# Load the required libraries at one place as a good practice
library(lsa)
library(reshape2)

```

# Set Working Directory

```{r}
# Set the working directory
  # setwd("")
```

# Read data into R

```{r}

data = read.csv("MovieRatings.csv",header=T)
head(data)
tail(data)
numOfUsers <-length(unique(data$UserID))
print(numOfUsers)
numOfMovies <- length(unique(data$Movie))
print(numOfMovies)
```

# Data Pre-processing

```{r}

# Covert the given data into matrix form
#UserID into rows & Movie into columns
??dcast
data2=dcast(data, UserID ~ Movie, value="Rating")
data2=data2[,c("UserID","M1","M2","M3","M4","M5","M6","M7","M8","M9","M10","M11","M12","M13","M14","M15","M16","M17","M18","M19")]
data2 <-data2[1:100,]
View(data2)

```

# Building the distance using eucledian Distance 

```{r}
euclid <- function(x1, x2) sqrt(sum((x1 - x2) ^ 2))
data1 <- data2[,-1]
```

## Function to find similar users

```{r}
Similar_Users <-function(x,z){
                                  dist = 0
                                  user = 0
                                  for(i in 1:nrow(data1))
                                  {
                                    # find the euclidean distance for the row to every other row in the dataset
                                    dist[i] = euclid(data1[x,],as.vector(data1[i,])) 
                                    user[i] = i
                                  }
                                  
                                  Distance<-data.frame(user,dist)
                                             
                                  Distance<-Distance[order(Distance$dist)] # ordering the distances

                                  #Finding the Top 'Z' Users apart from the given users
                                  TopZUsers<-Distance$user[1:z+1][!Distance$user[1:z+1] %in% c(x)]
                                  
                                  subset<-data2[which(data2$UserID %in% TopZUsers),]
                                  return(subset)
                               }
```

```{r}
Similar_Users(1,3)
```

# Singular-value decomposition

```{r}
  SVD = svd(data2[,-1])
# What are there available with  SVD
  names(SVD)
  
  s <- diag(SVD$d)
  u <- SVD$u
  v <- SVD$v
```

## Function to extract top Z nearest users with respect to the given user using cosine similarity

```{r}
SimilarUsers <- function(x,z)
    {
        score= 0
        user = 0
        for (i in 1:nrow(u)) 
        {
          score[i] =cosine(u[1,],as.vector(u[i,]))
          user[i] = i
        }
        Distance<-data.frame(user,score)
        Distance<-Distance[order(-Distance$score),]
        z=z+1
        TopZUsers<-Distance$user[1:z][!Distance$user[1:z]%in%c(x)]
        subset<-data2[which(data2$UserID %in% TopZUsers),]
        return(subset)
    }
```

```{r}
#Extract similar users
  SimilarUsers(1,3)
```

## Function to return expected rating

```{r}
ExpectedRating <- function(x, y, z)
    {
    score = 0
    user = 0
    
    for (i in 1:nrow(u)) #iterating on the u matrix
    {
      score[i] = cosine(u[x, ], as.vector(u[i, ]))
      user[i] = i
    }
    
    Distance <- data.frame(user, score)
    Distance <- Distance[order(-Distance$score), ]
    TopZUsers <- Distance$user[1:z + 1][!Distance$user[1:z + 1] %in% c(x)]
    subset <- data2[which(data2$UserID %in% TopZUsers), ]
    #print(subset)
    # print(data2[which(data2$UserID%in%x),])
    return(mean(subset[, y]))
  }
  
```

```{r}
#Expected rating for a given 'User and Movie'
names(data2)
```

```{r}

#Input "User" "Movie" "NNs"

print(ExpectedRating(1,"M13",3))

```


