---
title: "cute02"
author: "ARUNJUNAIKANI T"
date: "October 25, 2018"
output: html_document
---

```{r}
rm(list=ls(all=TRUE))
```

```{r}
setwd("E:\\R\\CSE7302c_CUTe")
```

```{r}
train_data=read.csv('train_data.csv', header = T)
test_data=read.csv('test_data.csv',header = T)
```

```{r}
summary(train_data)
str(train_data)
dim(train_data)
sum(is.na(train_data))
sum(is.na(test_data))
```

```{r}
row.names(train_data)=train_data$index
train_data$tax_paid[is.na(train_data$tax_paid)]=0
test_data$tax_paid[is.na(test_data$tax_paid)]=0
str(train_data)
```
### knnImputation on numerical data
```{r}
library(DMwR)
all_attr=colnames(train_data)
str(train_data)
num_attr=names(train_data[,!names(train_data) %in% c("working_sector","qualification","loan_taken","martial_status","index","occupation","relationship","ethnicity ","gender","country ")])
train_data[,num_attr] <- knnImputation(train_data[,num_attr])  # perform knn imputation.
sum(is.na(train_data))
test_data[,!names(test_data) %in% c("working_sector","qualification","martial_status","index","occupation","relationship","ethnicity ","gender","country ")]= knnImputation(test_data[,!names(test_data) %in% c("working_sector","qualification","martial_status","index","occupation","relationship","ethnicity ","gender","country ")])  # perform knn imputation.
sum(is.na(test_data))
```
### Central imputation on categorical data
```{r}
sum(is.na(train_data))
train_data_imp=centralImputation(train_data)
sum(is.na(train_data_imp))
summary(train_data_imp)
sum(is.na(train_data_imp))
sum(is.na(test_data))
test_data_imp=centralImputation(test_data)
sum(is.na(test_data_imp))

str(train_data_imp)
```
### Exploratory Data Analysis

```{r}
###EDA ON numerical data
library(ggplot2)
summary(train_data_imp$age)
boxplot (age ~ target, data = train_data_imp, 
         main = "Age distribution for different income levels",
         xlab = "Income Levels", ylab = "Age", col = "salmon")

summary(train_data_imp$years_of_education)
boxplot (years_of_education ~ target, data = train_data_imp, 
         main = "Education in no of years distribution for different income levels",
         xlab = "Income Levels", ylab = "years of education", col = "Red")

summary(train_data_imp$working_hours)
boxplot (working_hours ~ target, data = train_data_imp, 
         main = "working_hours distribution for different income levels",
         xlab = "Income Levels", ylab = "working hours", col = "Blue")



```
### corelation
```{r}
CorMat= cor(train_data_imp[,c("age","financial_weight","tax_paid","years_of_education","gain","loss","working_hours")])
CorMat

```

```{r}
train_data$target=as.factor(train_data$target)
```

### standardization the data
```{r}
library(caret)
std_obj <- preProcess(x = train_data[, !names(train_data) %in% c("target")],
                      method = c("center", "scale"))

train_data<- predict(std_obj, train_data)

test_data<- predict(std_obj, test_data)

```
### split into train validate and test
```{r}
library(caret)


set.seed(786)


train_rows <- createDataPartition(train_data_imp$target, p = 0.7, list = F)

train_data_of_train <- train_data_imp[train_rows, ]

test_data_of_train <- train_data_imp[-train_rows, ]
```
### baseline model
```{r}
model1 <- glm(target~., data = train_data_of_train, family = binomial)
summary(model1)
```
###
```{r}
prob_train <- predict(model1, type = "response")
library(ROCR)
```

```{r}
pred <- prediction(prob_train, train_data_of_train$target)
perf <- performance(pred, measure="tpr", x.measure="fpr")
plot(perf, col=rainbow(10), colorize=T, print.cutoffs.at=seq(0,1,0.05))
```
```{r}
perf_auc <- performance(pred, measure="auc")



auc <- perf_auc@y.values[[1]]

print(auc)

```

```{r}
prob_test <- predict(model1, test_data_of_train, type = "response")

preds_test <- ifelse(prob_test > 0.5, 1, 0)

test_data_labs <- test_data_of_train$target

conf_matrix <- table(test_data_labs, preds_test)

print(conf_matrix)
```

```{r}
specificity <- conf_matrix[1, 1]/sum(conf_matrix[1, ])

print(specificity)
```

```{r}
sensitivity <- conf_matrix[2, 2]/sum(conf_matrix[2, ])

print(sensitivity)

```

```{r}
accuracy <- sum(diag(conf_matrix))/sum(conf_matrix)

print(accuracy)
```

```{r}
library(caret)


confusionMatrix(as.factor(preds_test),as.factor(test_data_of_train$target))
```
```{r}
library(MASS)
model1_aic <- stepAIC(model1, direction = "both")
```
```{r}
str(train_data)
str(test_data)
```
```{r}
anss <- predict(model1, test_data_imp, type = "response")
ansss <- ifelse(anss > 0.5, 1, 0)
a=data.frame(ansss)
a
aa=write.csv(a,file="SampleSubmission1.csv")
```



